pub mod abi {
    #[repr(transparent)]
    pub struct SyscallNumber(pub u64);
    pub type SyscallArg = u64;
    pub type SyscallResult = u64;
}

#[derive(Clone, Copy)]
#[repr(u64)]
pub enum SyscallId {
    Read = 0,
    Write,
    Open,
    Close,
    Stat,
    Fstat,
    Lstat,
    Poll,
    Lseek,
    Mmap,
    Mprotect,
    Munmap,
    Brk,
    Rtatc,
    Fcntl,
    ioctl,
    Mknod,
    Access,
    Pipe,
    Select,
    SchedYield,
    Mremap,
    Msync,
    Mincore,
    Madvise,
    Shmget,
    Shmat,
    Shmctl,
    Dup,
    Dup2,
    Pause,
    Nanosleep,
    Getitimer,
    Alarm,
    Setitimer,
    Getpid,
    Sendfile,
    Socket,
    Connect,
    Accept,
    Sendto,
    Recvfrom,
    Sendmsg,
    Recvmsg,
    Shutdown,
    Bind,
    Listen,
    Getsockname,
    Getpeername,
    Socketpair,
    Setsockopt,
    Getsockopt,
    Clone,
    Fork,
    Vfork,
    Execve,
    Exit,
    Wait4,
    Kill,
    Uname,
    Semget,
    Semop,
    Semctl,
    Shmdt,
    Msgget,
    Msgsnd,
    Msgrcv,
    Msgctl,
    Fcntl64,
    Mmap2,
    Truncate64,
    Ftruncate64,
    Getcwd,
    Capget,
    Capset,
    Sigaltstack,
    Mkfifo,
    Mknodat,
    Futimesat,
    Newfstatat,
    Unlinkat,
    Renameat,
    Linkat,
    Symlinkat,
    Readlinkat,
    Fchmodat,
    Faccessat,
    Pselect6,
    Ppoll,
    Unshare,
    Set_robust_list,
    Get_robust_list,
    Splice,
    Tee,
    Sync_file_range,
    Vmsplice,
    Move_pages,
    Utimensat,
    Epoll_create,
    Epoll_ctl,
    Epoll_wait,
    Fallocate,
    Timerfd_settime,
    Timerfd_gettime,
    Accept4,
    Signalfd4,
    Eventfd2,
    Epoll_create1,
    Dup3,
    Pipe2,
    Inotify_init1,
    Inotify_add_watch,
    Inotify_rm_watch,
    Io_uring_setup,
    Io_uring_enter,
    Io_uring_register,
    Openat,
    Mkdirat,
    Mkyumodat,
    Fchownat,
    Futimens,
    Openat2,
    Epoll_pwait,
    Epoll_pwait2,
    Memfd_create,
    Kexec_file_load,
    Bpf,
    Execveat,
    Userfaultfd,
    Membarrier,
    Mlock2,
    Copy_file_range,
    Preadv2,
    Pwritev2,
    Pkey_mprotect,
    Pkey_alloc,
    Pkey_free,
    Statx,
    Io_pgetevents,
    Rseq,
    Pidfd_send_signal,
    Ioprio_set,
    Ioprio_get,
    Rt_sigaction,
    Rt_sigprocmask,
    Rt_sigreturn,
    Largefile,
}

#[repr(i64)]
pub enum Errno {
    EPERM = -1,
    ENOENT = -2,
    ESRCH = -3,
    EINTR = -4,
    EIO = -5,
    ENXIO = -6,
    E2BIG = -7,
    ENOEXEC = -8,
    EBADF = -9,
    ECHILD = -10,
    EAGAIN = -11,
    ENOMEM = -12,
    EACCES = -13,
    EFAULT = -14,
    ENOTBLK = -15,
    EBUSY = -16,
    EEXIST = -17,
    EXDEV = -18,
    ENODEV = -19,
    ENOTDIR = -20,
    EISDIR = -21,
    EINVAL = -22,
    ENFILE = -23,
    EMFILE = -24,
    ENOTTY = -25,
    ETXTBSY = -26,
    EFBIG = -27,
    ENOSPC = -28,
    ESPIPE = -29,
    EROFS = -30,
    EMLINK = -31,
    EPIPE = -32,
    EDOM = -33,
    ERANGE = -34,
}

